version: "3.7"
services:
    web:
        build: .
        image: mahzan-api
        container_name: mahzan-api-web
        ports:
        - "5000:5000"
        depends_on:
        - sql-server-db
    sql-server-db:
        container_name: sql-server-db
        image: microsoft/mssql-server-linux:2017-latest
        ports:
          - "1433:1433"
        environment:
          SA_PASSWORD: "Mahzan19%"
          ACCEPT_EULA: "Y"