//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahzan.Business.Resources.Validations.AspNetUsers {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogInValidationsResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogInValidationsResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mahzan.Business.Resources.Validations.AspNetUsers.LogInValidationsResources", typeof(LogInValidationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ValidSignInManager_Title {
            get {
                return ResourceManager.GetString("ValidSignInManager_Title", resourceCulture);
            }
        }
        
        internal static string ValidSignInManager_SUCCESS_Message {
            get {
                return ResourceManager.GetString("ValidSignInManager_SUCCESS_Message", resourceCulture);
            }
        }
        
        internal static string ValidSignInManager_400_ERROR_Message_IsLockedOut {
            get {
                return ResourceManager.GetString("ValidSignInManager_400_ERROR_Message_IsLockedOut", resourceCulture);
            }
        }
        
        internal static string ValidSignInManager_400_ERROR_Message_AspNetUser {
            get {
                return ResourceManager.GetString("ValidSignInManager_400_ERROR_Message_AspNetUser", resourceCulture);
            }
        }
    }
}
