//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahzan.Business.Resources.Validations.Companies {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddCompaniesValidationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddCompaniesValidationsResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mahzan.Business.Resources.Validations.Companies.AddCompaniesValidationsResources", typeof(AddCompaniesValidationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha validado correctamente la información del Empresa..
        /// </summary>
        internal static string Add_Valid_200_SUCCESS_Message {
            get {
                return ResourceManager.GetString("Add_Valid_200_SUCCESS_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Grupo {0} no existe..
        /// </summary>
        internal static string Add_Valid_500_WARNING_Message_GroupsId {
            get {
                return ResourceManager.GetString("Add_Valid_500_WARNING_Message_GroupsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El RFC de la Empresa ya existe..
        /// </summary>
        internal static string Add_Valid_500_WARNING_Message_RFC {
            get {
                return ResourceManager.GetString("Add_Valid_500_WARNING_Message_RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La estructura del RFC no es correcto favor de validar..
        /// </summary>
        internal static string Add_Valid_500_WARNING_Message_RFC_No_Valid {
            get {
                return ResourceManager.GetString("Add_Valid_500_WARNING_Message_RFC_No_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valida información de la Empresa..
        /// </summary>
        internal static string Add_Valid_Title {
            get {
                return ResourceManager.GetString("Add_Valid_Title", resourceCulture);
            }
        }
    }
}
